<?php

namespace App\Services;

use App\Mail\TripRescheduledMail;
use App\Models\AuditLog;
use App\Models\Booking;
use App\Models\Passenger;
use App\Models\ScheduleTemplate;
use App\Models\TripSchedule;
use App\Support\ManilaClock;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

/**
 * Service to orchestrate atomic cascading updates, deletions, and
 * Option A Auto-Rescheduling for Recurring Schedule Templates and future trip instances.
 */
class RecurringScheduleCascadeService
{
    public function __construct(
        private readonly FcmPushService $fcmPushService,
        private readonly RecurringScheduleGenerator $generator,
        private readonly BookingService $bookingService
    ) {
    }

    /**
     * Cascade delete a recurring schedule template and manage its future trips.
     *
     * 1. Unbooked future trips (booked_seats_count == 0) are deleted immediately.
     * 2. Booked future trips (booked_seats_count > 0) undergo Option A Auto-Reschedule:
     *    - Shift passengers to nearest available trip on or BEFORE original date.
     *    - Fall back to next available date AFTER original date if no earlier trip has seats.
     *    - Reassign seats, update bookings, dispatch FCM + Email alerts.
     *    - Delete original trip instance once all bookings are transferred.
     * 3. Delete the template record.
     *
     * @param ScheduleTemplate $template
     * @return array{deleted_unbooked: int, rescheduled_booked: int, affected_passengers: int}
     */
    public function cascadeDelete(ScheduleTemplate $template): array
    {
        return DB::transaction(function () use ($template) {
            $templateId = $template->id;
            $route = $template->route;
            $now = ManilaClock::now();

            // Locate all future trips generated by this template that are still Scheduled
            $futureTrips = TripSchedule::where('schedule_template_id', $templateId)
                ->where('status', 'Scheduled')
                ->where('departure_time', '>=', $now)
                ->with(['boat', 'bookings' => fn ($q) => $q->where('status', '!=', 'cancelled')])
                ->lockForUpdate()
                ->get();

            $deletedUnbookedCount = 0;
            $rescheduledBookedCount = 0;
            $affectedPassengersCount = 0;

            foreach ($futureTrips as $trip) {
                $activeBookings = $trip->bookings;

                if ($activeBookings->isEmpty()) {
                    // Unbooked trip: hard delete immediately
                    $trip->delete();
                    $deletedUnbookedCount++;
                } else {
                    // Booked trip: execute Option A Auto-Reschedule
                    $moved = $this->autoRescheduleTripBookings(
                        $trip,
                        "Recurring rule #{$templateId} was deleted by administration",
                        $templateId
                    );

                    $affectedPassengersCount += count($moved['reassigned_bookings']);
                    $rescheduledBookedCount++;
                }
            }

            // Finally, delete the template
            $template->delete();

            AuditLog::record(
                'schedule',
                'Recurring Schedule Cascade Deleted',
                "Deleted recurring rule #{$templateId} ({$route}). Cleaned {$deletedUnbookedCount} unbooked trip(s) and auto-rescheduled {$rescheduledBookedCount} booked trip(s) ({$affectedPassengersCount} passenger booking(s) moved)."
            );

            return [
                'deleted_unbooked' => $deletedUnbookedCount,
                'rescheduled_booked' => $rescheduledBookedCount,
                'affected_passengers' => $affectedPassengersCount,
            ];
        });
    }

    /**
     * Cascade update a recurring schedule template and synchronize future trips.
     *
     * 1. Modified departure/arrival times: Update future trips and booking time slots, notify passengers.
     * 2. Modified recurring days:
     *    - Excluded days: Delete unbooked trips, auto-reschedule booked trips.
     *    - Retained days: Update times and details.
     * 3. Spawn missing trip instances for new days within the 7-day lookahead horizon.
     *
     * @param ScheduleTemplate $template
     * @param array<string, mixed> $oldAttributes
     * @param array<string, mixed> $newAttributes
     * @return array{
     *     removed_unbooked: int,
     *     rescheduled_booked: int,
     *     time_updated_trips: int,
     *     time_updated_bookings: int,
     *     newly_spawned: int
     * }
     */
    public function cascadeUpdate(ScheduleTemplate $template, array $oldAttributes, array $newAttributes): array
    {
        return DB::transaction(function () use ($template, $oldAttributes, $newAttributes) {
            $now = ManilaClock::now();

            // Locate all future trips currently generated by this template
            $futureTrips = TripSchedule::where('schedule_template_id', $template->id)
                ->where('status', 'Scheduled')
                ->where('departure_time', '>=', $now)
                ->with(['boat', 'bookings' => fn ($q) => $q->where('status', '!=', 'cancelled')])
                ->lockForUpdate()
                ->get();

            $removedUnbookedCount = 0;
            $rescheduledBookedCount = 0;
            $timeUpdatedTripsCount = 0;
            $timeUpdatedBookingsCount = 0;

            $oldDepTime = $oldAttributes['departure_time'] ?? null;
            $newDepTime = $newAttributes['departure_time'] ?? $template->departure_time;

            $oldArrTime = $oldAttributes['arrival_time'] ?? null;
            $newArrTime = $newAttributes['arrival_time'] ?? $template->arrival_time;

            $timeChanged = ($oldDepTime !== $newDepTime) || ($oldArrTime !== $newArrTime);

            foreach ($futureTrips as $trip) {
                $tripDate = $trip->departure_time->copy()->startOfDay();

                // 1. Check if this date is still part of the updated recurring pattern
                if (!$template->appliesToDate($tripDate)) {
                    // Date was removed from recurrence (e.g. Daily -> Mon/Wed/Fri, and this is Tuesday)
                    if ($trip->bookings->isEmpty()) {
                        $trip->delete();
                        $removedUnbookedCount++;
                    } else {
                        $this->autoRescheduleTripBookings(
                            $trip,
                            "Recurring rule days updated to {$template->formatted_recurrence}",
                            null
                        );
                        $rescheduledBookedCount++;
                    }
                    continue;
                }

                // 2. Date is retained: synchronize departure and arrival times if changed
                if ($timeChanged) {
                    $depParts = explode(':', $newDepTime);
                    $newDeparture = $tripDate->copy()
                        ->timezone(ManilaClock::TIMEZONE)
                        ->setTime((int) ($depParts[0] ?? 0), (int) ($depParts[1] ?? 0), 0);

                    // Arrival calculation
                    if ($newArrTime) {
                        $arrParts = explode(':', $newArrTime);
                        $newArrival = $tripDate->copy()
                            ->timezone(ManilaClock::TIMEZONE)
                            ->setTime((int) ($arrParts[0] ?? 0), (int) ($arrParts[1] ?? 0), 0);
                        if ($newArrival->lte($newDeparture)) {
                            $newArrival->addDay();
                        }
                    } else {
                        $newArrival = $newDeparture->copy()->addHours(2);
                    }

                    $oldTripSnapshot = [
                        'date' => $trip->departure_time->format('M d, Y'),
                        'departure_time' => $trip->departure_time->format('g:i A'),
                        'boat_name' => $trip->boat?->name ?? 'Ferry Vessel',
                    ];

                    $trip->departure_time = $newDeparture;
                    $trip->arrival_time = $newArrival;
                    $trip->save();
                    $timeUpdatedTripsCount++;

                    // Update associated bookings and notify passengers of time change
                    foreach ($trip->bookings as $booking) {
                        $booking->departure_time_slot = $newDeparture->format('H:i');
                        $booking->notes = trim(($booking->notes ? $booking->notes . ' ' : '') . "[Time updated to {$newDeparture->format('g:i A')}]");
                        $booking->save();
                        $timeUpdatedBookingsCount++;

                        $this->notifyPassengerOfScheduleChange(
                            $booking,
                            $trip,
                            $oldTripSnapshot,
                            "Departure time adjusted from {$oldTripSnapshot['departure_time']} to {$newDeparture->format('g:i A')}"
                        );
                    }
                }
            }

            // 3. Generate any missing trips for newly matching days across the 3-month (90-day) lookahead horizon
            $genResult = $this->generator->generateForTemplate($template, RecurringScheduleGenerator::LOOKAHEAD_DAYS);
            $newlySpawnedCount = $genResult['generated_count'];

            AuditLog::record(
                'schedule',
                'Recurring Schedule Cascade Synchronized',
                "Updated recurring rule #{$template->id}: adjusted {$timeUpdatedTripsCount} trip time(s), notified {$timeUpdatedBookingsCount} passenger(s), removed {$removedUnbookedCount} unbooked trip(s), rescheduled {$rescheduledBookedCount} booked trip(s), spawned {$newlySpawnedCount} new trip(s)."
            );

            return [
                'removed_unbooked' => $removedUnbookedCount,
                'rescheduled_booked' => $rescheduledBookedCount,
                'time_updated_trips' => $timeUpdatedTripsCount,
                'time_updated_bookings' => $timeUpdatedBookingsCount,
                'newly_spawned' => $newlySpawnedCount,
            ];
        });
    }

    /**
     * Move all active bookings from an original trip to an optimal alternative trip (Option A).
     * Once all bookings are moved, deletes the original trip instance.
     *
     * @param TripSchedule $origTrip
     * @param string $reason
     * @param int|null $excludingTemplateId If deleting a template, do not reschedule onto its trips
     * @return array{reassigned_bookings: array<int, Booking>, target_trip: ?TripSchedule}
     */
    public function autoRescheduleTripBookings(TripSchedule $origTrip, string $reason, ?int $excludingTemplateId = null): array
    {
        $bookings = $origTrip->bookings()->where('status', '!=', 'cancelled')->get();

        if ($bookings->isEmpty()) {
            $origTrip->delete();
            return ['reassigned_bookings' => [], 'target_trip' => null];
        }

        $totalSeatsNeeded = 0;
        foreach ($bookings as $b) {
            $seats = $b->seat_numbers;
            $totalSeatsNeeded += is_array($seats) ? count($seats) : (empty($seats) ? 1 : count(explode(',', (string) $seats)));
        }

        // Find candidate trip according to Option A priority
        $targetTrip = $this->findBestAlternativeTrip($origTrip, $totalSeatsNeeded, $excludingTemplateId);

        $oldTripSnapshot = [
            'date' => $origTrip->departure_time->format('M d, Y'),
            'departure_time' => $origTrip->departure_time->format('g:i A'),
            'boat_name' => $origTrip->boat?->name ?? 'Ferry Vessel',
        ];

        if ($targetTrip) {
            $reassigned = [];

            foreach ($bookings as $booking) {
                $seatCount = is_array($booking->seat_numbers)
                    ? count($booking->seat_numbers)
                    : (empty($booking->seat_numbers) ? 1 : count(explode(',', (string) $booking->seat_numbers)));

                // Allocate seats from target trip
                $allocatedSeats = $this->allocateSeatsOnTrip($targetTrip, $seatCount, $booking->passenger_name);

                // Update booking details
                $booking->trip_schedule_id = $targetTrip->id;
                $booking->trip_date = $targetTrip->departure_time->format('Y-m-d');
                $booking->departure_time_slot = $targetTrip->departure_time->format('H:i');
                $booking->seat_numbers = $allocatedSeats;
                $booking->notes = trim(($booking->notes ? $booking->notes . ' ' : '') . "[Auto-Rescheduled from Trip #{$origTrip->id} on {$oldTripSnapshot['date']} {$oldTripSnapshot['departure_time']}]");
                $booking->save();

                $reassigned[] = $booking;

                // Send FCM Push + In-App Notification + Email
                $this->notifyPassengerOfScheduleChange($booking, $targetTrip, $oldTripSnapshot, $reason);
            }

            // Delete the old trip now that all passengers have been safely moved
            $origTrip->delete();

            return [
                'reassigned_bookings' => $reassigned,
                'target_trip' => $targetTrip,
            ];
        }

        // Fallback: If absolutely no other trip exists with available capacity across the system,
        // preserve the trip as an independent standalone trip (detach from template) so passengers are never stranded
        $origTrip->schedule_template_id = null;
        $origTrip->notes = trim(($origTrip->notes ? $origTrip->notes . ' ' : '') . "[Preserved as Standalone Trip - {$reason}]");
        $origTrip->save();

        Log::warning("[RecurringScheduleCascadeService] No candidate alternative trip with {$totalSeatsNeeded} seats found for Trip #{$origTrip->id}. Preserved as standalone trip.");

        return [
            'reassigned_bookings' => $bookings->all(),
            'target_trip' => $origTrip,
        ];
    }

    /**
     * Find the best alternative trip for Option A Auto-Reschedule:
     * 1. Nearest available trip on or BEFORE original date (Priority 1: Shift Tuesday to Monday, ordered by departure_time DESC).
     * 2. Fall back to next available trip AFTER original date (Priority 2: ordered by departure_time ASC).
     *
     * @param TripSchedule $origTrip
     * @param int $seatsNeeded
     * @param int|null $excludingTemplateId
     * @return TripSchedule|null
     */
    public function findBestAlternativeTrip(TripSchedule $origTrip, int $seatsNeeded, ?int $excludingTemplateId = null): ?TripSchedule
    {
        $now = ManilaClock::now();
        $origDeparture = $origTrip->departure_time;

        $baseQuery = TripSchedule::query()
            ->where('id', '!=', $origTrip->id)
            ->where('route', $origTrip->route)
            ->where('status', 'Scheduled')
            ->where('departure_time', '>=', $now)
            ->where('available_seats', '>=', $seatsNeeded);

        if ($excludingTemplateId) {
            $baseQuery->where(function ($q) use ($excludingTemplateId) {
                $q->whereNull('schedule_template_id')
                    ->orWhere('schedule_template_id', '!=', $excludingTemplateId);
            });
        }

        // Priority 1 (Backward): Nearest trip on or BEFORE the original departure date
        $priorTrip = (clone $baseQuery)
            ->where('departure_time', '<=', $origDeparture)
            ->orderBy('departure_time', 'desc')
            ->first();

        if ($priorTrip) {
            return $priorTrip;
        }

        // Priority 2 (Forward Fallback): Next available trip AFTER the original departure date
        $postTrip = (clone $baseQuery)
            ->where('departure_time', '>', $origDeparture)
            ->orderBy('departure_time', 'asc')
            ->first();

        return $postTrip;
    }

    /**
     * Allocate $count open seats on target trip's seat_map and deduct available_seats.
     *
     * @param TripSchedule $trip
     * @param int $count
     * @param string|null $passengerName
     * @return array<int, string> Assigned seat codes (e.g. ["1A", "1B"])
     */
    protected function allocateSeatsOnTrip(TripSchedule $trip, int $count, ?string $passengerName = null): array
    {
        $seatMap = $trip->seat_map;
        $assignedCodes = [];
        $needed = $count;

        foreach ($seatMap as $idx => $seat) {
            if ($needed <= 0) {
                break;
            }

            $isBooked = !empty($seat['booked']) || strtolower((string) ($seat['status'] ?? '')) === 'booked';
            if (!$isBooked) {
                $seatMap[$idx]['booked'] = true;
                $seatMap[$idx]['status'] = 'booked';
                $seatMap[$idx]['passenger_name'] = $passengerName;
                $assignedCodes[] = $seat['seat_number'] ?? (string) ($idx + 1);
                $needed--;
            }
        }

        // If not enough discrete seats in map (or map was empty), generate sequential codes
        while ($needed > 0) {
            $code = "S" . ($trip->boat?->passenger_capacity ?? 40 - $needed);
            $assignedCodes[] = $code;
            $needed--;
        }

        $trip->seat_map = $seatMap;
        $trip->available_seats = max(0, (int) $trip->available_seats - count($assignedCodes));
        $trip->save();

        return $assignedCodes;
    }

    /**
     * Dispatch multi-channel notifications (In-App Database, FCM Push, and Email) to passenger.
     */
    protected function notifyPassengerOfScheduleChange(
        Booking $booking,
        TripSchedule $newTrip,
        ?array $oldTripData,
        string $reason
    ): void {
        $title = "Important: SeaPass Trip Schedule Update";
        $body = "Your trip ({$newTrip->route}) is now departing on {$newTrip->departure_time->format('M d, Y')} at {$newTrip->departure_time->format('g:i A')} on {$newTrip->boat?->name}.";

        // 1. In-App Notification & FCM Push
        if ($booking->passenger_id) {
            $passenger = Passenger::find($booking->passenger_id);
            if ($passenger) {
                $this->fcmPushService->sendToPassenger(
                    $passenger,
                    $title,
                    $body,
                    [
                        'booking_id' => $booking->id,
                        'reference_number' => $booking->reference_number,
                        'trip_id' => $newTrip->id,
                        'departure_time' => $newTrip->departure_time->toIso8601String(),
                        'reason' => $reason,
                    ]
                );
            }
        }

        // 2. Email Notification
        if (!empty($booking->email)) {
            try {
                Mail::to($booking->email)->queue(
                    new TripRescheduledMail($booking, $newTrip, $oldTripData, $reason)
                );
            } catch (\Throwable $e) {
                Log::warning("[RecurringScheduleCascadeService] Failed to queue reschedule email to {$booking->email}: " . $e->getMessage());
            }
        }
    }
}
